Repository dehadeaaryan/superfrogschedulerbackend, pull requests merged in 2024-04, with the labels that each got.

#8 Feature create student object
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/student/Student.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/student/StudentController.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/student/StudentRepository.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/student/StudentService.java
Labels: enhancement

#7 Feature create payment object
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/StudentPayment/StudentPayment.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/StudentPayment/StudentPaymentController.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/StudentPayment/StudentPaymentRepository.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/StudentPayment/StudentPaymentService.java
Labels: enhancement

#14 Renamed package to lowercase
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/studentpayment/StudentPayment.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/studentpayment/StudentPaymentController.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/studentpayment/StudentPaymentRepository.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/studentpayment/StudentPaymentService.java
Labels: enhancement

#17 Feature uc1
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/calendar/Calendar.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/calendar/CalendarController.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/calendar/CalendarRepository.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/calendar/CalendarService.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/request/Request.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/request/RequestController.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/request/RequestNotFoundException.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/request/RequestService.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/schedule/Schedule.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/spiritdirector/SpiritDirector.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/spiritdirector/SpiritDirectorController.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/spiritdirector/SpiritDirectorRepository.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/spiritdirector/SpiritDirectorService.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/student/Student.java
  src/test/java/edu/tcu/cs/superfrogschedulerbackend/request/RequestControllerTest.java
  src/test/java/edu/tcu/cs/superfrogschedulerbackend/request/RequestServiceTest.java
Labels: enhancement

#19 Edited application.yml (from application.properties)
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/calendar/CalendarController.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/calendar/converter/CalendarToCalendarDtoConverter.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/request/RequestController.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/schedule/ScheduleController.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/spiritdirector/SpiritDirectorController.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/student/converter/StudentToStudentDtoConverter.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/studentpayment/StudentPaymentController.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: bug, enhancement

#22 USE ObjectNotFoundException instead of independent variations
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/request/RequestNotFoundException.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/request/RequestService.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/student/StudentNotFoundException.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/student/StudentService.java
  src/test/java/edu/tcu/cs/superfrogschedulerbackend/request/RequestControllerTest.java
  src/test/java/edu/tcu/cs/superfrogschedulerbackend/request/RequestServiceTest.java
Labels: enhancement

#25 Request CRUD + RequestService Tests
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/request/Request.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/request/RequestController.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/request/RequestService.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/request/converter/RequestDtoToRequestConverter.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/request/converter/RequestToRequestDtoConverter.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/request/dto/RequestDto.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/schedule/Schedule.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/schedule/ScheduleController.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/schedule/ScheduleRepository.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/schedule/ScheduleService.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/studenttimes/StudentTimes.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/studenttimes/dto/StudentTimeDto.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/system/DBDataInitializer.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/system/exception/ObjectNotFoundException.java
  src/test/java/edu/tcu/cs/superfrogschedulerbackend/request/RequestControllerTest.java
  src/test/java/edu/tcu/cs/superfrogschedulerbackend/request/RequestServiceTest.java
Labels: enhancement

#28 Feature uc1
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/request/RequestService.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/request/converter/RequestDtoToRequestConverter.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/request/converter/RequestToRequestDtoConverter.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/request/dto/RequestDto.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/security/CorsConfiguration.java
  src/test/java/edu/tcu/cs/superfrogschedulerbackend/request/RequestControllerTest.java
Labels: enhancement

#29 Edits
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/request/RequestService.java
Labels: enhancement

#30 Feature uc20
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/student/StudentController.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/student/StudentService.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/student/converter/StudentDtoToStudent.java
Labels: enhancement

#34 Feature studenttimes
  pom.xml
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/request/Request.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/student/Student.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/student/StudentController.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/student/StudentService.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/student/converter/StudentToStudentDtoConverter.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/student/dto/StudentDto.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/studenttimes/StudentTimes.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/studenttimes/StudentTimesController.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/studenttimes/StudentTimesService.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/studenttimes/converter/StudentTimeDtoToStudentTime.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/studenttimes/converter/StudentTimeToStudentTimeDtoConverter.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/studenttimes/dto/StudentTimeDto.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/system/DBDataInitializer.java
Labels: enhancement

#35 Update Student Time to use days of week instead of dates
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/studenttimes/StudentTimes.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/studenttimes/converter/StudentTimeDtoToStudentTime.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/studenttimes/converter/StudentTimeToStudentTimeDtoConverter.java
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/studenttimes/dto/StudentTimeDto.java
Labels: bug, enhancement

#36 Fix db init
  src/main/java/edu/tcu/cs/superfrogschedulerbackend/system/DBDataInitializer.java
Labels: bug
